### ISSUE TITLE
Crash on startup with version pre2a

### ISSUE THREAD

**Issue by AvrgDerk** [UselessSolutions/BTA_Babric_LegacyUI#39]
crashes immediately on start.

Prism Launcher version: 8.2 (flatpak)

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::71, 2620:1ec:46::71, 13.107.246.71, 13.107.213.71]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::71, 2620:1ec:46::71, 13.107.246.71, 13.107.213.71]

api.mojang.com resolves to:
    [2620:1ec:bdf::71, 2620:1ec:46::71, 13.107.246.71, 13.107.213.71]

Minecraft folder is:
/home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/bta/.minecraft

Java path is:
/app/jdk/8/jre/bin/java

Java is version 1.8.0_402, using 64 (amd64) architecture, from Oracle Corporation.

Failed to resolve server address (this is NOT an error!) _minecraft._tcp.: Non existent domain

AMD Custom APU 0405
Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405] (rev ae)

Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device 0123

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.3 (git-c4d371fa7e)

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/bta/natives

Traits:
traits legacyServices
traits noapplet
traits legacyLaunch
traits texturepacks

Libraries:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-babric.1/lwjgl-2.9.4-babric.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-babric.1/lwjgl_util-2.9.4-babric.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/babric/log4j-config/1.0.0/log4j-config-1.0.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/mapping-io/0.5.0/mapping-io-0.5.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-remapper/0.10.0/tiny-remapper-0.10.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/github/llamalad7/mixinextras-fabric/0.3.2/mixinextras-fabric-0.3.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/bta/libraries/fabric-loader-0.15.6-babric.4-bta.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/bta/.minecraft/bin/minecraft.jar

Native libraries:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-babric.1/lwjgl-platform-2.9.4-babric.1-natives-linux.jar

Mods:
  [✔] bta_controller_support-1.0.0-7.1
  [✔] halplibe-3.4.14
  [✔] halplibe-3.4.16
  [✔] legacyui-1.1.2-7.1
  [✔] modmenu-bta-2.0.4
  [✔] prismaticlibe-3.0.3-7.1

Jar Mods:
  Better than Adventure! (bta.jar)

Params:
  --username  --session  --gameDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/bta/.minecraft --assetsDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/bta/.minecraft/resources

Window size: 854 x 480

Launcher: legacy

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 616

ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[10:49:25] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 7.1 Prerelease 2a with Fabric Loader 0.15.6-babric.4-bta
[10:49:25] [main/INFO] (FabricLoader) Loading 10 mods:
	- controller_support 1.0.0-7.1
	- fabricloader 0.15.6-babric.4-bta+local
	   \-- mixinextras 0.3.2
	- halplibe 3.4.16
	   \-- org_apache_commons_commons-lang3 3.12.0
	- java 8
	- legacyui 1.1.2-7.1
	- minecraft 7.1-beta.2a
	- modmenu 2.0.4
	- prismaticlibe 3.0.3-7.1
[10:49:25] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:49:26] [main/INFO] (halplibe) Config file name: halplibe.cfg
[10:49:26] [main/INFO] (halplibe) Config file path: /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/bta/.minecraft/config/halplibe.cfg
[10:49:26] [main/INFO] (FabricLoader/MixinExtras|Service) Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[10:49:26] [main/INFO] (FabricLoader/Mixin) halplibe.mixins.json:accessors.BlockFireAccessor from mod halplibe->@Invoker[METHOD_PROXY]::callSetBurnRate(III)V should be static as its target is
0 Achievements
[10:49:26] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/core/sound/SoundType (java.lang.ClassNotFoundException: net/minecraft/core/sound/SoundType)
[10:49:26] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod legacyui failed legacyui.mixins.json:Gui.GuiScreenMixin from mod legacyui -> net.minecraft.client.gui.GuiScreen: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> legacyui.mixins.json:Gui.GuiScreenMixin from mod legacyui -> Apply Methods -> (Lnet/minecraft/client/sound/SoundManager;Ljava/lang/String;Lnet/minecraft/core/sound/SoundType;FF)V:redirect$zdc000$legacyui$legacySound -> Transform LVT -> var=soundType -> desc=Lnet/minecraft/core/sound/SoundType;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> legacyui.mixins.json:Gui.GuiScreenMixin from mod legacyui -> Apply Methods -> (Lnet/minecraft/client/sound/SoundManager;Ljava/lang/String;Lnet/minecraft/core/sound/SoundType;FF)V:redirect$zdc000$legacyui$legacySound -> Transform LVT -> var=soundType -> desc=Lnet/minecraft/core/sound/SoundType;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:535) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:521) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.6-babric.4-bta.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.6-babric.4-bta.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.6-babric.4-bta.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.6-babric.4-bta.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_402]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_402]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) [?:1.8.0_402]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) [?:1.8.0_402]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386) [?:1.8.0_402]
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780) [?:1.8.0_402]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471) [fabric-loader-0.15.6-babric.4-bta.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.6-babric.4-bta.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.6-babric.4-bta.jar:?]
	at org.prismlauncher.legacy.LegacyLauncher.launch(LegacyLauncher.java:123) [NewLaunchLegacy.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.core.sound.SoundType
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1001) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:961) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:563) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:469) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 25 more
Exception caught from launcher
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.gui.GuiScreen failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.legacy.LegacyLauncher.launch(LegacyLauncher.java:123)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 15 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [legacyui.mixins.json:Gui.GuiScreenMixin from mod legacyui] from phase [DEFAULT] in config [legacyui.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> legacyui.mixins.json:Gui.GuiScreenMixin from mod legacyui -> Apply Methods -> (Lnet/minecraft/client/sound/SoundManager;Ljava/lang/String;Lnet/minecraft/core/sound/SoundType;FF)V:redirect$zdc000$legacyui$legacySound -> Transform LVT -> var=soundType -> desc=Lnet/minecraft/core/sound/SoundType;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:535)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:521)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.core.sound.SoundType
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1001)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:961)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:469)
	... 25 more
Exiting with ERROR
Process exited with code 2.

**Comment by AzaleaCatgirl99** [comment]
The mod hasn't been updated to 7.1pre2a yet. Please use 7.1pre1a instead.
