### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by Pasithea0** [UselessSolutions/BTA_Babric_LegacyUI#42]
Log:
```

     Minecraft has crashed!
     ----------------------

Minecraft has stopped running because it encountered a problem.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.
Please include a description of what you did when the error occured.


     System Information
     ------------------

Generated 6/28/24, 10:25 PM
Minecraft: Better than Adventure! 7.1_01
OS: Mac OS X (aarch64) version 14.5
Java: 22, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
LWJGL: 2.9.4
OpenGL: Apple M2 Pro version 2.1 Metal - 88.1, Apple


     Error Information
     ------------------

The following exception caused the crash handler to open:
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "net.minecraft.core.item.Item.getKey()" is null
	at useless.legacyui.Sorting.UtilSorting.stackInKeywordList(UtilSorting.java:36)
	at useless.legacyui.Sorting.Item.ItemCategoryBuilder.build(ItemCategoryBuilder.java:196)
	at useless.legacyui.Sorting.LegacyCategoryManager.build(LegacyCategoryManager.java:31)
	at net.minecraft.client.Minecraft.handler$zbi000$legacyui$startOfGameInit(Minecraft.java:4548)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:482)
	at net.minecraft.client.Minecraft.run(Minecraft.java:738)
	at java.base/java.lang.Thread.run(Thread.java:1570)


The following exception occured while trying to render the crash handler:
java.lang.NullPointerException: Cannot invoke "useless.legacyui.Settings.ILegacyOptions.getEnablePanorama()" because "useless.legacyui.LegacyUI.modSettings" is null
	at net.minecraft.client.gui.GuiMainMenu.handler$zcm000$legacyui$panorama(GuiMainMenu.java:557)
	at net.minecraft.client.gui.GuiMainMenu.drawBackground(GuiMainMenu.java)
	at net.minecraft.client.gui.GuiScreen.drawWorldBackground(GuiScreen.java:177)
	at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:166)
	at net.minecraft.client.gui.GuiMainMenu.drawScreen(GuiMainMenu.java:305)
	at net.minecraft.client.gui.popup.GuiPopup.drawScreen(GuiPopup.java:167)
	at net.minecraft.client.render.WorldRenderer.updateCameraAndRender(WorldRenderer.java:576)
	at net.minecraft.client.Minecraft.run(Minecraft.java:842)
	at java.base/java.lang.Thread.run(Thread.java:1570)



```

I also tried java 17 and got the same error so that wasn't the problem.

Better Than Legacy! 1.2.1-7.1
HalpLibe 3.5.4
Mod Menu 2.0.5
Prismatic Library 3.1.2-7.1

**Comment by envyniv** [comment]
Using PrismaticLibe 3.1.1 seems to work. Evidently something changed in 3.1.2 that's causing this.
